### PR TITLE
Case-insensitive extension check for attachments

### PR DESCRIPTION
**Pull request by boboldehampsink**
Had a client that wanted to upload a .PDF file which failed because of this.

### CODE REVIEW

**Comment by boboldehampsink** [comment]
cc @angrybrad

**Comment by andris-sevcenko** [comment]
@boboldehampsink any chance you could add a changelog entry for this?

**Comment by boboldehampsink** [comment]
@andris-sevcenko updated changelog and bumped version

**Comment by andris-sevcenko** [comment]
Boom.

**Pull request merged**
