### PR TITLE
Make it easier to add custom validation

### PR DESCRIPTION
**Pull request by nstCactus**
### Description

As suggested in the PHPdoc of the Yii `Model::defineRules()` method:

> Models should override this method instead of [[rules()]] so [[EVENT_DEFINE_RULES]] handlers can modify the class-defined rules.

### CODE REVIEW

**Comment by ademers** [comment]
I want to make the `fromName` and `subject` fields required, so in a custom module, I added:

```php
Event::on(
    Submission::class,
    Submission::EVENT_DEFINE_RULES,
    function(DefineRulesEvent $event) {
        $event->rules[] = [['fromName', 'subject'], 'required'];
    }
);
```

However, it only works when I change `public function rules()` to `public function defineRules(): array` in `Submission.php`.

**Comment by MoritzLost** [comment]
Any status update on this? Changing the method from `rules` to `defineRules` shouldn't change the behaviour and make it much easier to add custom validation.

**Comment by ademers** [comment]
Would really like to see this implemented!

**Comment by AugustMiller** [comment]
Discovered with @bencroker that this might be a breaking change, because `Model::defineRules()` is only available in Craft ^3.4.0…

**Comment by nstCactus** [comment]
@AugustMiller Wouldn't it be possible to bump the required Craft CMS version to 3.4 in composer.json for the next version?
That way, the plugin would still be compatible with old Craft CMS installs in its current version but users of Craft CMS > 3.4 would get new versions.

**Comment by brandonkelly** [comment]
Thanks @nstCactus! Just merged and released as 2.3.0.

**Pull request merged**
