### PR TITLE
New message from {systemName}

### PR DESCRIPTION
**Pull request by carlcs**
Nicer default email subject when site names are named after locales and the subject reads “New message from English“.

### CODE REVIEW

**Comment by angrybrad** [comment]
I dunno... seems like having the current site name is better behavior for multi-site installs? At least you can tell which site it's coming from at a glance.

**Comment by carlcs** [comment]
That’s true, the site name can work better for multi-site installs. System name shouldn’t be too bad though and it’s a trade-off I’d make to have useful default messages when sites are used for localization (more common use case still, I guess).

**Comment by carlcs** [comment]
I don’t have string feelings about it though. 😄 An email with subject “New message from English“ in my inbox brought me here (GitHub makes is too easy to make quick edits + PRs)…

**Comment by angrybrad** [comment]
Hah... given that and it's easy enough to change the message to whatever you want, going to go ahead and close this one out.

**Pull request closed without merging**
